# Generated by Django 5.1.3 on 2024-11-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0002_useraddress_userpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpayment',
            name='expiry_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
