# Generated by Django 5.1.2 on 2024-11-16 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0003_alter_userpayment_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_profile',
            field=models.ImageField(null=True, upload_to='user/'),
        ),
    ]
