# Generated by Django 5.1.2 on 2024-11-16 06:41

import userauths.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0004_alter_user_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_profile',
            field=models.ImageField(null=True, upload_to=userauths.models.user_directory_path),
        ),
    ]
