# Generated by Django 5.1.2 on 2024-11-16 07:07

import userauths.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0005_alter_user_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_profile',
            field=models.ImageField(default='../static/assets/imgs/human.png', null=True, upload_to=userauths.models.user_directory_path),
        ),
    ]
