# Generated by Django 5.1.3 on 2024-11-21 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0006_alter_user_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='road',
        ),
    ]
