# Generated by Django 5.1.3 on 2024-11-21 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0007_remove_useraddress_road'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddress',
            old_name='member',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='useraddress',
            old_name='member_address_id',
            new_name='user_address_id',
        ),
        migrations.RenameField(
            model_name='userpayment',
            old_name='member',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='userpayment',
            old_name='member_payment_id',
            new_name='user_payment_id',
        ),
    ]
