# Generated by Django 5.1.2 on 2024-11-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0008_rename_member_useraddress_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpayment',
            name='account_no',
        ),
        migrations.RemoveField(
            model_name='userpayment',
            name='payment_type',
        ),
        migrations.RemoveField(
            model_name='userpayment',
            name='provider',
        ),
        migrations.AddField(
            model_name='userpayment',
            name='card_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userpayment',
            name='card_provider',
            field=models.CharField(blank=True, choices=[('debit', 'Debit'), ('visa', 'Visa'), ('mastercard', 'Mastercard')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='userpayment',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
