# Generated by Django 5.1.2 on 2024-11-23 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0009_remove_userpayment_account_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_privilege',
            field=models.IntegerField(choices=[(1, 'User'), (2, 'Admin'), (3, 'Dev')], default=1),
        ),
    ]
