# Generated by Django 5.1.2 on 2024-11-23 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0010_user_user_privilege'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_privilege',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=1),
        ),
    ]
