# Generated by Django 5.1.2 on 2024-11-23 09:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0011_alter_user_user_privilege'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_privilege',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)]),
        ),
    ]
