# Generated by Django 5.1.3 on 2024-11-23 18:33

import phonenumber_field.modelfields
import userauths.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauths", "0012_alter_user_user_privilege"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(default="John", max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(default="Mayer", max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="telephone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default="0000000000", max_length=128, region=None, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="user_profile",
            field=models.ImageField(
                default="./static/assets/imgs/human.png",
                null=True,
                upload_to=userauths.models.user_directory_path,
            ),
        ),
        migrations.AlterField(
            model_name="useraddress",
            name="postal_code",
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name="useraddress",
            name="telephone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region=None
            ),
        ),
        migrations.AlterField(
            model_name="userpayment",
            name="card_no",
            field=models.CharField(max_length=20),
        ),
        migrations.AddConstraint(
            model_name="useraddress",
            constraint=models.UniqueConstraint(
                fields=(
                    "user_address_id",
                    "user",
                    "address",
                    "city",
                    "province",
                    "postal_code",
                    "telephone",
                ),
                name="unique_user_address",
            ),
        ),
        migrations.AddConstraint(
            model_name="userpayment",
            constraint=models.UniqueConstraint(
                fields=(
                    "user_payment_id",
                    "user",
                    "card_provider",
                    "card_no",
                    "expiry_date",
                ),
                name="unique_user_payment",
            ),
        ),
    ]
