# Generated by Django 5.1.3 on 2024-11-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0013_alter_user_first_name_alter_user_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userpayment',
            name='unique_user_payment',
        ),
        migrations.AddConstraint(
            model_name='userpayment',
            constraint=models.UniqueConstraint(fields=('user_payment_id', 'user', 'card_provider', 'card_no', 'expiry_date'), name='unique_user_payment'),
        ),
    ]
