# Generated by Django 5.1.3 on 2024-11-23 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0015_alter_user_telephone_alter_useraddress_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpayment',
            name='card_provider',
            field=models.CharField(choices=[('debit', 'Debit'), ('visa', 'Visa'), ('mastercard', 'Mastercard')], max_length=15),
        ),
        migrations.AlterField(
            model_name='userpayment',
            name='expiry_date',
            field=models.DateField(),
        ),
    ]
