# Generated by Django 5.1.2 on 2024-11-25 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0016_alter_userpayment_card_provider_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAddress',
        ),
        migrations.DeleteModel(
            name='UserPayment',
        ),
        # migrations.RemoveField(
        #     model_name='userpayment',
        #     name='user',
        # ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='John', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='Mayer', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.CharField(default='000000000', max_length=13),
        ),
        
    ]
