# Generated by Django 5.1.2 on 2024-11-25 12:33

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0017_remove_userpayment_user_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefhghijklmnopqrtuvwxyz1234567890', length=10, max_length=20, prefix='user', primary_key=True, serialize=False, unique=True),
        ),
    ]
