# Generated by Django 5.1.2 on 2024-11-25 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0018_remove_user_id_alter_user_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('user_address_id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('province', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=5)),
                ('telephone', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user_address_id', 'user', 'address', 'city', 'province', 'postal_code', 'telephone'), name='unique_user_address')],
            },
        ),
        migrations.CreateModel(
            name='UserPayment',
            fields=[
                ('user_payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('card_provider', models.CharField(choices=[('debit', 'Debit'), ('visa', 'Visa'), ('mastercard', 'Mastercard')], max_length=15)),
                ('card_no', models.CharField(max_length=20)),
                ('expiry_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user_payment_id', 'user', 'card_provider', 'card_no', 'expiry_date'), name='unique_user_payment')],
            },
        ),
    ]
