# Generated by Django 5.1.3 on 2024-11-10 15:42

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_type', models.CharField(max_length=255)),
                ('provider', models.CharField(max_length=255)),
                ('total_price', models.FloatField(default=0)),
                ('status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='name of a product', max_length=100)),
                ('description', models.TextField(blank=True, default='This is a product', null=True)),
                ('image', models.ImageField(default='product.png', upload_to='product/')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=99999999)),
                ('quantity', models.IntegerField(default=0)),
                ('product_type', models.CharField(default='sword', max_length=20)),
                ('uniform_size', models.IntegerField(default=30, null=True)),
                ('sword_length', models.IntegerField(default=30, null=True)),
                ('armor_color', models.TextField(blank=True, default='red')),
                ('armor_size', models.IntegerField(default=30, null=True)),
                ('product_status', models.CharField(choices=[('available', 'Available'), ('not available', 'Not Available'), ('out of stock', 'Out of Stock')], default='available', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('code', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('discount', models.FloatField(default=0.15)),
                ('amount', models.IntegerField(default=1000)),
                ('end_date', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('member', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('payment', models.OneToOneField(default=0, on_delete=django.db.models.deletion.RESTRICT, to='core.payment')),
                ('promotion_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.promotion')),
            ],
        ),
        migrations.CreateModel(
            name='CanceledOrder',
            fields=[
                ('canceled_order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('order_item_id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('order', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.order')),
                ('product', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sessions.session')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('cart_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shoppingsession')),
            ],
        ),
    ]
