# Generated by Django 5.1.3 on 2024-11-08 05:25

import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefhghijklmnopqrtuvwxyz1234567890', length=10, max_length=20, prefix='prod', unique=True)),
                ('name', models.CharField(default='name of a product', max_length=100)),
                ('description', models.TextField(blank=True, default='This is a product', null=True)),
                ('image', models.ImageField(default='product.png', upload_to='product/')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=99999999)),
                ('quantity', models.IntegerField(default=0)),
                ('product_type', models.CharField(default='sword', max_length=20)),
                ('uniform_size', models.IntegerField(default=30, null=True)),
                ('sword_length', models.IntegerField(default=30, null=True)),
                ('armor_color', models.TextField(blank=True, default='red')),
                ('armor_size', models.IntegerField(default=30, null=True)),
                ('product_status', models.CharField(choices=[('available', 'Available'), ('not available', 'Not Available'), ('out of stock', 'Out of Stock')], default='available', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
    ]
