# Generated by Django 5.1.2 on 2024-11-05 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('product_type', models.TextField()),
                ('uniform_size', models.IntegerField(null=True)),
                ('sword_length', models.IntegerField(null=True)),
                ('armor_color', models.TextField(blank=True)),
                ('armor_size', models.IntegerField(null=True)),
            ],
        ),
    ]
