# Generated by Django 5.1.2 on 2024-11-05 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('cart_item_id', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingSession',
            fields=[
                ('session_id', models.UUIDField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
