# Generated by Django 5.1.2 on 2024-11-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingsession',
            name='user',
        ),
        migrations.AlterField(
            model_name='product',
            name='armor_color',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
