# Generated by Django 5.1.2 on 2024-11-19 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_shoppingsession_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='armor_color',
            new_name='uniform_color',
        ),
    ]
