# Generated by Django 5.1.3 on 2024-11-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_product_armor_color_alter_product_armor_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('sword', 'Sword'), ('armor', 'Armor'), ('uniform', 'Uniform')], default='sword', max_length=20),
        ),
    ]
