# Generated by Django 5.1.2 on 2024-11-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_armor_color_product_uniform_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uniform_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
