# Generated by Django 5.1.2 on 2024-11-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_product_armor_size_alter_product_sword_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='armor_size',
            field=models.CharField(blank=True, choices=[('', ''), ('xs', 'Extra Small'), ('s', 'Small'), ('m', 'Medium'), ('l', 'Large'), ('xl', 'Extra Large')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sword_length',
            field=models.CharField(blank=True, choices=[('', ''), ('28', '28'), ('30', '30'), ('32', '32'), ('34', '34'), ('36', '36'), ('37', '37'), ('37W', '37 Women'), ('38', '38'), ('38w', '38 Woman'), ('39', '39'), ('39w', '39 Woman')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='uniform_size',
            field=models.CharField(blank=True, choices=[('', ''), ('xs', 'Extra Small'), ('s', 'Small'), ('m', 'Medium'), ('l', 'Large'), ('xl', 'Extra Large')], max_length=3, null=True),
        ),
    ]
