# Generated by Django 5.1.3 on 2024-11-23 19:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_order_member_remove_order_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2025, 11, 24, 2, 24, 20, 962127)),
        ),
    ]
