# Generated by Django 5.1.2 on 2024-11-25 12:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_promotion_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2025, 11, 25, 12, 43, 0, 831811)),
        ),
    ]
