# Generated by Django 5.1.2 on 2024-11-25 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_promotion_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=99999999, max_length=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.AutoField(max_length=9, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0, max_length=9),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='amount',
            field=models.IntegerField(default=1000, max_length=9),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='discount',
            field=models.FloatField(default=0.15, max_length=5),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2025, 11, 25, 13, 19, 28, 711997)),
        ),
    ]
