# Generated by Django 5.1.3 on 2024-11-21 07:37

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0008_remove_order_member_remove_order_payment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_type', models.CharField(max_length=255)),
                ('provider', models.CharField(max_length=255)),
                ('total_price', models.FloatField(default=0)),
                ('status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('member', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('promotion_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.promotion')),
                ('payment', models.OneToOneField(default=0, on_delete=django.db.models.deletion.RESTRICT, to='payment.payment')),
            ],
        ),
        migrations.CreateModel(
            name='CanceledOrder',
            fields=[
                ('canceled_order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='payment.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('order_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('order', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='payment.order')),
                ('product', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
        ),
    ]
