# Generated by Django 5.1.3 on 2024-11-21 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='status',
        ),
        migrations.AddField(
            model_name='payment',
            name='card_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='card_provider',
            field=models.CharField(blank=True, choices=[('debit', 'Debit'), ('visa', 'Visa'), ('mastercard', 'Mastercard')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='card_status',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='cash_status',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='qr_status',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='canceledorder',
            name='order',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='payment.order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='member',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('qr', 'QrCode'), ('card', 'Card')], max_length=15, null=True),
        ),
    ]
