# Generated by Django 5.1.3 on 2024-11-23 19:24

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_order_shipping_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canceledorder',
            name='order',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='payment.order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='postal_code',
            field=models.CharField(default='11120', max_length=5),
        ),
        migrations.AlterField(
            model_name='order',
            name='telephone',
            field=models.CharField(default='00000000', max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('qr', 'QrCode'), ('card', 'Card')], default='cash', max_length=15),
        ),
    ]
