# Generated by Django 5.1.2 on 2024-11-25 12:43

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_promotion_end_date'),
        ('payment', '0008_remove_order_payment_remove_order_promotion_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(default='100/100', max_length=255)),
                ('city', models.CharField(default='Parkret', max_length=255)),
                ('province', models.CharField(default='Nonthaburi', max_length=255)),
                ('postal_code', models.CharField(default='11120', max_length=5)),
                ('telephone', models.CharField(default='00000000', max_length=10)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('shipping_status', models.BooleanField(default=False)),
                ('payment', models.OneToOneField(default=0, on_delete=django.db.models.deletion.RESTRICT, to='payment.payment')),
                ('promotion_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.promotion')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CanceledOrder',
            fields=[
                ('canceled_order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='payment.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('order_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('order', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='payment.order')),
                ('product', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
        ),
    ]
