# Generated by Django 5.1.2 on 2024-11-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_order_canceledorder_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canceledorder',
            name='canceled_order_id',
            field=models.AutoField(max_length=9, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.AutoField(max_length=9, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order_item_id',
            field=models.AutoField(max_length=9, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=1, max_length=9),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.AutoField(max_length=9, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='total_price',
            field=models.FloatField(default=0, max_length=9),
        ),
    ]
