# Generated by Django 5.1.3 on 2024-11-21 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='cart_item_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
