# Generated by Django 5.1.3 on 2024-11-21 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cartitem_cart_item_id'),
        ('core', '0008_remove_order_member_remove_order_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingsession',
            name='promotion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.promotion'),
        ),
    ]
