# Generated by Django 5.1.3 on 2024-11-21 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_shoppingsession_promotion'),
        ('core', '0008_remove_order_member_remove_order_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingsession',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.promotion'),
        ),
    ]
