# Generated by Django 5.1.2 on 2024-11-25 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_shoppingsession_promotion'),
        ('core', '0010_alter_promotion_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingsession',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.promotion'),
        ),
    ]
