# Generated by Django 5.1.2 on 2024-11-25 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_shoppingsession_promotion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingsession',
            name='promotion',
        ),
        migrations.RemoveField(
            model_name='shoppingsession',
            name='user',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='ShoppingSession',
        ),
    ]
